version: '3.8'
services:
  db:
    container_name: recycle_chain_db
    image: postgres
    restart: always
    ports:
      - 2024:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_recycle_chain:/var/lib/postgresql/data
volumes:
  db_data_recycle_chain:
